/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiCallback;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiClient;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiResponse;
import io.kestra.plugin.atlassian_confluence.client.invoker.Configuration;
import io.kestra.plugin.atlassian_confluence.client.invoker.Pair;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressRequestBody;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.kestra.plugin.atlassian_confluence.client.model.GetViewers200Response;
import io.kestra.plugin.atlassian_confluence.client.model.GetViews200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AnalyticsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AnalyticsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AnalyticsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getViewers
     * @param contentId The ID of the content to get the viewers for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of distinct viewers for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViewersCall(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/analytics/content/{contentId}/viewers"
            .replace("{" + "contentId" + "}", localVarApiClient.escapeString(contentId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (fromDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("fromDate", fromDate));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getViewersValidateBeforeCall(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'contentId' is set
        if (contentId == null) {
            throw new ApiException("Missing the required parameter 'contentId' when calling getViewers(Async)");
        }

        return getViewersCall(contentId, fromDate, _callback);

    }

    /**
     * Get viewers
     * Get the total number of distinct viewers a piece of content has.
     * @param contentId The ID of the content to get the viewers for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @return GetViewers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of distinct viewers for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public GetViewers200Response getViewers(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate) throws ApiException {
        ApiResponse<GetViewers200Response> localVarResp = getViewersWithHttpInfo(contentId, fromDate);
        return localVarResp.getData();
    }

    /**
     * Get viewers
     * Get the total number of distinct viewers a piece of content has.
     * @param contentId The ID of the content to get the viewers for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @return ApiResponse&lt;GetViewers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of distinct viewers for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetViewers200Response> getViewersWithHttpInfo(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate) throws ApiException {
        okhttp3.Call localVarCall = getViewersValidateBeforeCall(contentId, fromDate, null);
        Type localVarReturnType = new TypeToken<GetViewers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get viewers (asynchronously)
     * Get the total number of distinct viewers a piece of content has.
     * @param contentId The ID of the content to get the viewers for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of distinct viewers for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViewersAsync(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate, final ApiCallback<GetViewers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getViewersValidateBeforeCall(contentId, fromDate, _callback);
        Type localVarReturnType = new TypeToken<GetViewers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getViews
     * @param contentId The ID of the content to get the views for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of views for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViewsCall(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/analytics/content/{contentId}/views"
            .replace("{" + "contentId" + "}", localVarApiClient.escapeString(contentId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (fromDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("fromDate", fromDate));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getViewsValidateBeforeCall(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'contentId' is set
        if (contentId == null) {
            throw new ApiException("Missing the required parameter 'contentId' when calling getViews(Async)");
        }

        return getViewsCall(contentId, fromDate, _callback);

    }

    /**
     * Get views
     * Get the total number of views a piece of content has.
     * @param contentId The ID of the content to get the views for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @return GetViews200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of views for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public GetViews200Response getViews(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate) throws ApiException {
        ApiResponse<GetViews200Response> localVarResp = getViewsWithHttpInfo(contentId, fromDate);
        return localVarResp.getData();
    }

    /**
     * Get views
     * Get the total number of views a piece of content has.
     * @param contentId The ID of the content to get the views for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @return ApiResponse&lt;GetViews200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of views for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetViews200Response> getViewsWithHttpInfo(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate) throws ApiException {
        okhttp3.Call localVarCall = getViewsValidateBeforeCall(contentId, fromDate, null);
        Type localVarReturnType = new TypeToken<GetViews200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get views (asynchronously)
     * Get the total number of views a piece of content has.
     * @param contentId The ID of the content to get the views for. (required)
     * @param fromDate The number of views for the content since the date. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the total number of views for the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if client input is invalid. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the authentication credentials are missing from the request. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no content with the given ID. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViewsAsync(@javax.annotation.Nonnull String contentId, @javax.annotation.Nullable String fromDate, final ApiCallback<GetViews200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getViewsValidateBeforeCall(contentId, fromDate, _callback);
        Type localVarReturnType = new TypeToken<GetViews200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
