/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiCallback;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiClient;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiResponse;
import io.kestra.plugin.atlassian_confluence.client.invoker.Configuration;
import io.kestra.plugin.atlassian_confluence.client.invoker.Pair;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressRequestBody;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.kestra.plugin.atlassian_confluence.client.model.Version;
import io.kestra.plugin.atlassian_confluence.client.model.VersionRestore;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ContentVersionsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ContentVersionsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ContentVersionsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteContentVersion
     * @param id The ID of the content that the version will be deleted from. (required)
     * @param versionNumber The number of the version to be deleted. The version number starts from 1 up to current version. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the version is deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The content or version cannot be found. - The current version is specified. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteContentVersionCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Integer versionNumber, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/content/{id}/version/{versionNumber}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "versionNumber" + "}", localVarApiClient.escapeString(versionNumber.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteContentVersionValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Integer versionNumber, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteContentVersion(Async)");
        }

        // verify the required parameter 'versionNumber' is set
        if (versionNumber == null) {
            throw new ApiException("Missing the required parameter 'versionNumber' when calling deleteContentVersion(Async)");
        }

        return deleteContentVersionCall(id, versionNumber, _callback);

    }

    /**
     * Delete content version
     * Delete a historical version. This does not delete the changes made to the content in that version, rather the changes for the deleted version are rolled up into the next version. Note, you cannot delete the current version.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the version will be deleted from. (required)
     * @param versionNumber The number of the version to be deleted. The version number starts from 1 up to current version. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the version is deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The content or version cannot be found. - The current version is specified. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public void deleteContentVersion(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Integer versionNumber) throws ApiException {
        deleteContentVersionWithHttpInfo(id, versionNumber);
    }

    /**
     * Delete content version
     * Delete a historical version. This does not delete the changes made to the content in that version, rather the changes for the deleted version are rolled up into the next version. Note, you cannot delete the current version.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the version will be deleted from. (required)
     * @param versionNumber The number of the version to be deleted. The version number starts from 1 up to current version. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the version is deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The content or version cannot be found. - The current version is specified. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteContentVersionWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Integer versionNumber) throws ApiException {
        okhttp3.Call localVarCall = deleteContentVersionValidateBeforeCall(id, versionNumber, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete content version (asynchronously)
     * Delete a historical version. This does not delete the changes made to the content in that version, rather the changes for the deleted version are rolled up into the next version. Note, you cannot delete the current version.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the version will be deleted from. (required)
     * @param versionNumber The number of the version to be deleted. The version number starts from 1 up to current version. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the version is deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The content or version cannot be found. - The current version is specified. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteContentVersionAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Integer versionNumber, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteContentVersionValidateBeforeCall(id, versionNumber, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for restoreContentVersion
     * @param id The ID of the content for which the history will be restored. (required)
     * @param body The content version to be restored. (required)
     * @param expand A multi-value parameter indicating which properties of the content to expand. By default, the &#x60;content&#x60; object is expanded.  - &#x60;collaborators&#x60; returns the users that collaborated on the version. - &#x60;content&#x60; returns the content for the version. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the version is restored. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - There is no content with the given ID. - There is no version with the given version number. - The version number is the current version. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call restoreContentVersionCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull VersionRestore body, @javax.annotation.Nullable List<String> expand, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/content/{id}/version"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (expand != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("csv", "expand", expand));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call restoreContentVersionValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull VersionRestore body, @javax.annotation.Nullable List<String> expand, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling restoreContentVersion(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling restoreContentVersion(Async)");
        }

        return restoreContentVersionCall(id, body, expand, _callback);

    }

    /**
     * Restore content version
     * Restores a historical version to be the latest version. That is, a new version is created with the content of the historical version.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content for which the history will be restored. (required)
     * @param body The content version to be restored. (required)
     * @param expand A multi-value parameter indicating which properties of the content to expand. By default, the &#x60;content&#x60; object is expanded.  - &#x60;collaborators&#x60; returns the users that collaborated on the version. - &#x60;content&#x60; returns the content for the version. (optional)
     * @return Version
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the version is restored. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - There is no content with the given ID. - There is no version with the given version number. - The version number is the current version. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public Version restoreContentVersion(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull VersionRestore body, @javax.annotation.Nullable List<String> expand) throws ApiException {
        ApiResponse<Version> localVarResp = restoreContentVersionWithHttpInfo(id, body, expand);
        return localVarResp.getData();
    }

    /**
     * Restore content version
     * Restores a historical version to be the latest version. That is, a new version is created with the content of the historical version.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content for which the history will be restored. (required)
     * @param body The content version to be restored. (required)
     * @param expand A multi-value parameter indicating which properties of the content to expand. By default, the &#x60;content&#x60; object is expanded.  - &#x60;collaborators&#x60; returns the users that collaborated on the version. - &#x60;content&#x60; returns the content for the version. (optional)
     * @return ApiResponse&lt;Version&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the version is restored. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - There is no content with the given ID. - There is no version with the given version number. - The version number is the current version. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Version> restoreContentVersionWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull VersionRestore body, @javax.annotation.Nullable List<String> expand) throws ApiException {
        okhttp3.Call localVarCall = restoreContentVersionValidateBeforeCall(id, body, expand, null);
        Type localVarReturnType = new TypeToken<Version>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Restore content version (asynchronously)
     * Restores a historical version to be the latest version. That is, a new version is created with the content of the historical version.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content for which the history will be restored. (required)
     * @param body The content version to be restored. (required)
     * @param expand A multi-value parameter indicating which properties of the content to expand. By default, the &#x60;content&#x60; object is expanded.  - &#x60;collaborators&#x60; returns the users that collaborated on the version. - &#x60;content&#x60; returns the content for the version. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the version is restored. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - There is no content with the given ID. - There is no version with the given version number. - The version number is the current version. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user doesn&#39;t have permission to edit the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call restoreContentVersionAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull VersionRestore body, @javax.annotation.Nullable List<String> expand, final ApiCallback<Version> _callback) throws ApiException {

        okhttp3.Call localVarCall = restoreContentVersionValidateBeforeCall(id, body, expand, _callback);
        Type localVarReturnType = new TypeToken<Version>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
