/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiCallback;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiClient;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiResponse;
import io.kestra.plugin.atlassian_confluence.client.invoker.Configuration;
import io.kestra.plugin.atlassian_confluence.client.invoker.Pair;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressRequestBody;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.kestra.plugin.atlassian_confluence.client.model.AddLabelsToContentRequest;
import io.kestra.plugin.atlassian_confluence.client.model.LabelArray;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ContentLabelsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ContentLabelsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ContentLabelsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addLabelsToContent
     * @param id The ID of the content that will have labels added to it. (required)
     * @param body The labels to add to the content. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLabelsToContentCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull AddLabelsToContentRequest body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/content/{id}/label"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addLabelsToContentValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull AddLabelsToContentRequest body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling addLabelsToContent(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling addLabelsToContent(Async)");
        }

        return addLabelsToContentCall(id, body, _callback);

    }

    /**
     * Add labels to content
     * Adds labels to a piece of content. Does not modify the existing labels.  Notes:  - Labels can also be added when creating content ([Create content](#api-content-post)). - Labels can be updated when updating content ([Update content](#api-content-id-put)). This will delete the existing labels and replace them with the labels in the request.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that will have labels added to it. (required)
     * @param body The labels to add to the content. (required)
     * @return LabelArray
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public LabelArray addLabelsToContent(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull AddLabelsToContentRequest body) throws ApiException {
        ApiResponse<LabelArray> localVarResp = addLabelsToContentWithHttpInfo(id, body);
        return localVarResp.getData();
    }

    /**
     * Add labels to content
     * Adds labels to a piece of content. Does not modify the existing labels.  Notes:  - Labels can also be added when creating content ([Create content](#api-content-post)). - Labels can be updated when updating content ([Update content](#api-content-id-put)). This will delete the existing labels and replace them with the labels in the request.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that will have labels added to it. (required)
     * @param body The labels to add to the content. (required)
     * @return ApiResponse&lt;LabelArray&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LabelArray> addLabelsToContentWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull AddLabelsToContentRequest body) throws ApiException {
        okhttp3.Call localVarCall = addLabelsToContentValidateBeforeCall(id, body, null);
        Type localVarReturnType = new TypeToken<LabelArray>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add labels to content (asynchronously)
     * Adds labels to a piece of content. Does not modify the existing labels.  Notes:  - Labels can also be added when creating content ([Create content](#api-content-post)). - Labels can be updated when updating content ([Update content](#api-content-id-put)). This will delete the existing labels and replace them with the labels in the request.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that will have labels added to it. (required)
     * @param body The labels to add to the content. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLabelsToContentAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull AddLabelsToContentRequest body, final ApiCallback<LabelArray> _callback) throws ApiException {

        okhttp3.Call localVarCall = addLabelsToContentValidateBeforeCall(id, body, _callback);
        Type localVarReturnType = new TypeToken<LabelArray>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for removeLabelFromContent
     * @param id The ID of the content that the label will be removed from. (required)
     * @param label The name of the label to be removed. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the label name has a \&quot;/\&quot; character. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeLabelFromContentCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String label, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/content/{id}/label/{label}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "label" + "}", localVarApiClient.escapeString(label.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call removeLabelFromContentValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String label, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling removeLabelFromContent(Async)");
        }

        // verify the required parameter 'label' is set
        if (label == null) {
            throw new ApiException("Missing the required parameter 'label' when calling removeLabelFromContent(Async)");
        }

        return removeLabelFromContentCall(id, label, _callback);

    }

    /**
     * Remove label from content
     * Removes a label from a piece of content. Labels can&#39;t be deleted from archived content. This is similar to [Remove label from content using query parameter](#api-content-id-label-delete) except that the label name is specified via a path parameter.  Use this method if the label name does not have \&quot;/\&quot; characters, as the path parameter does not accept \&quot;/\&quot; characters for security reasons. Otherwise, use [Remove label from content using query parameter](#api-content-id-label-delete).  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the label will be removed from. (required)
     * @param label The name of the label to be removed. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the label name has a \&quot;/\&quot; character. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public void removeLabelFromContent(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String label) throws ApiException {
        removeLabelFromContentWithHttpInfo(id, label);
    }

    /**
     * Remove label from content
     * Removes a label from a piece of content. Labels can&#39;t be deleted from archived content. This is similar to [Remove label from content using query parameter](#api-content-id-label-delete) except that the label name is specified via a path parameter.  Use this method if the label name does not have \&quot;/\&quot; characters, as the path parameter does not accept \&quot;/\&quot; characters for security reasons. Otherwise, use [Remove label from content using query parameter](#api-content-id-label-delete).  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the label will be removed from. (required)
     * @param label The name of the label to be removed. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the label name has a \&quot;/\&quot; character. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> removeLabelFromContentWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String label) throws ApiException {
        okhttp3.Call localVarCall = removeLabelFromContentValidateBeforeCall(id, label, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Remove label from content (asynchronously)
     * Removes a label from a piece of content. Labels can&#39;t be deleted from archived content. This is similar to [Remove label from content using query parameter](#api-content-id-label-delete) except that the label name is specified via a path parameter.  Use this method if the label name does not have \&quot;/\&quot; characters, as the path parameter does not accept \&quot;/\&quot; characters for security reasons. Otherwise, use [Remove label from content using query parameter](#api-content-id-label-delete).  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the label will be removed from. (required)
     * @param label The name of the label to be removed. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the label name has a \&quot;/\&quot; character. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeLabelFromContentAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String label, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeLabelFromContentValidateBeforeCall(id, label, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for removeLabelFromContentUsingQueryParameter
     * @param id The ID of the content that the label will be removed from. (required)
     * @param name The name of the label to be removed. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeLabelFromContentUsingQueryParameterCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/content/{id}/label"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call removeLabelFromContentUsingQueryParameterValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String name, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling removeLabelFromContentUsingQueryParameter(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling removeLabelFromContentUsingQueryParameter(Async)");
        }

        return removeLabelFromContentUsingQueryParameterCall(id, name, _callback);

    }

    /**
     * Remove label from content using query parameter
     * Removes a label from a piece of content. Labels can&#39;t be deleted from archived content. This is similar to [Remove label from content](#api-content-id-label-label-delete) except that the label name is specified via a query parameter.  Use this method if the label name has \&quot;/\&quot; characters, as [Remove label from content using query parameter](#api-content-id-label-delete) does not accept \&quot;/\&quot; characters for the label name.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the label will be removed from. (required)
     * @param name The name of the label to be removed. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public void removeLabelFromContentUsingQueryParameter(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String name) throws ApiException {
        removeLabelFromContentUsingQueryParameterWithHttpInfo(id, name);
    }

    /**
     * Remove label from content using query parameter
     * Removes a label from a piece of content. Labels can&#39;t be deleted from archived content. This is similar to [Remove label from content](#api-content-id-label-label-delete) except that the label name is specified via a query parameter.  Use this method if the label name has \&quot;/\&quot; characters, as [Remove label from content using query parameter](#api-content-id-label-delete) does not accept \&quot;/\&quot; characters for the label name.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the label will be removed from. (required)
     * @param name The name of the label to be removed. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> removeLabelFromContentUsingQueryParameterWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String name) throws ApiException {
        okhttp3.Call localVarCall = removeLabelFromContentUsingQueryParameterValidateBeforeCall(id, name, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Remove label from content using query parameter (asynchronously)
     * Removes a label from a piece of content. Labels can&#39;t be deleted from archived content. This is similar to [Remove label from content](#api-content-id-label-label-delete) except that the label name is specified via a query parameter.  Use this method if the label name has \&quot;/\&quot; characters, as [Remove label from content using query parameter](#api-content-id-label-delete) does not accept \&quot;/\&quot; characters for the label name.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param id The ID of the content that the label will be removed from. (required)
     * @param name The name of the label to be removed. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label is removed. The response body will be empty. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The calling user does not have permission to view the content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call removeLabelFromContentUsingQueryParameterAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String name, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = removeLabelFromContentUsingQueryParameterValidateBeforeCall(id, name, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
