/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiCallback;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiClient;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiResponse;
import io.kestra.plugin.atlassian_confluence.client.invoker.Configuration;
import io.kestra.plugin.atlassian_confluence.client.invoker.Pair;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressRequestBody;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.kestra.plugin.atlassian_confluence.client.model.LabelArray;
import io.kestra.plugin.atlassian_confluence.client.model.LabelCreate;
import io.kestra.plugin.atlassian_confluence.client.model.LongTask;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ExperimentalApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ExperimentalApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ExperimentalApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addLabelsToSpace
     * @param spaceKey The key of the space to add labels to. (required)
     * @param labelCreate The labels to add to the content. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLabelsToSpaceCall(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull List<LabelCreate> labelCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = labelCreate;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/space/{spaceKey}/label"
            .replace("{" + "spaceKey" + "}", localVarApiClient.escapeString(spaceKey.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addLabelsToSpaceValidateBeforeCall(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull List<LabelCreate> labelCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'spaceKey' is set
        if (spaceKey == null) {
            throw new ApiException("Missing the required parameter 'spaceKey' when calling addLabelsToSpace(Async)");
        }

        // verify the required parameter 'labelCreate' is set
        if (labelCreate == null) {
            throw new ApiException("Missing the required parameter 'labelCreate' when calling addLabelsToSpace(Async)");
        }

        return addLabelsToSpaceCall(spaceKey, labelCreate, _callback);

    }

    /**
     * Add labels to a space
     * Adds labels to a piece of content. Does not modify the existing labels.  Notes:  - Labels can also be added when creating content ([Create content](#api-content-post)). - Labels can be updated when updating content ([Update content](#api-content-id-put)). This will delete the existing labels and replace them with the labels in the request.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param spaceKey The key of the space to add labels to. (required)
     * @param labelCreate The labels to add to the content. (required)
     * @return LabelArray
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public LabelArray addLabelsToSpace(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull List<LabelCreate> labelCreate) throws ApiException {
        ApiResponse<LabelArray> localVarResp = addLabelsToSpaceWithHttpInfo(spaceKey, labelCreate);
        return localVarResp.getData();
    }

    /**
     * Add labels to a space
     * Adds labels to a piece of content. Does not modify the existing labels.  Notes:  - Labels can also be added when creating content ([Create content](#api-content-post)). - Labels can be updated when updating content ([Update content](#api-content-id-put)). This will delete the existing labels and replace them with the labels in the request.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param spaceKey The key of the space to add labels to. (required)
     * @param labelCreate The labels to add to the content. (required)
     * @return ApiResponse&lt;LabelArray&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LabelArray> addLabelsToSpaceWithHttpInfo(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull List<LabelCreate> labelCreate) throws ApiException {
        okhttp3.Call localVarCall = addLabelsToSpaceValidateBeforeCall(spaceKey, labelCreate, null);
        Type localVarReturnType = new TypeToken<LabelArray>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add labels to a space (asynchronously)
     * Adds labels to a piece of content. Does not modify the existing labels.  Notes:  - Labels can also be added when creating content ([Create content](#api-content-post)). - Labels can be updated when updating content ([Update content](#api-content-id-put)). This will delete the existing labels and replace them with the labels in the request.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to update the content.
     * @param spaceKey The key of the space to add labels to. (required)
     * @param labelCreate The labels to add to the content. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the labels are added to the content. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if;  - The body contains labels with invalid characters or too many characters. - The body contains too many labels. - The target content would contain too many labels after the operation. - The calling user does not have permission to edit labels. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can view but not edit the content. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLabelsToSpaceAsync(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull List<LabelCreate> labelCreate, final ApiCallback<LabelArray> _callback) throws ApiException {

        okhttp3.Call localVarCall = addLabelsToSpaceValidateBeforeCall(spaceKey, labelCreate, _callback);
        Type localVarReturnType = new TypeToken<LabelArray>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteLabelFromSpace
     * @param spaceKey The key of the space to remove a labels from. (required)
     * @param name The name of the label to remove (required)
     * @param prefix The prefix of the label to remove. If not provided defaults to global. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if; - The user does not provide a label name </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteLabelFromSpaceCall(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull String name, @javax.annotation.Nullable String prefix, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/space/{spaceKey}/label"
            .replace("{" + "spaceKey" + "}", localVarApiClient.escapeString(spaceKey.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        if (prefix != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("prefix", prefix));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteLabelFromSpaceValidateBeforeCall(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull String name, @javax.annotation.Nullable String prefix, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'spaceKey' is set
        if (spaceKey == null) {
            throw new ApiException("Missing the required parameter 'spaceKey' when calling deleteLabelFromSpace(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling deleteLabelFromSpace(Async)");
        }

        return deleteLabelFromSpaceCall(spaceKey, name, prefix, _callback);

    }

    /**
     * Remove label from a space
     * 
     * @param spaceKey The key of the space to remove a labels from. (required)
     * @param name The name of the label to remove (required)
     * @param prefix The prefix of the label to remove. If not provided defaults to global. (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if; - The user does not provide a label name </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public void deleteLabelFromSpace(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull String name, @javax.annotation.Nullable String prefix) throws ApiException {
        deleteLabelFromSpaceWithHttpInfo(spaceKey, name, prefix);
    }

    /**
     * Remove label from a space
     * 
     * @param spaceKey The key of the space to remove a labels from. (required)
     * @param name The name of the label to remove (required)
     * @param prefix The prefix of the label to remove. If not provided defaults to global. (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if; - The user does not provide a label name </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteLabelFromSpaceWithHttpInfo(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull String name, @javax.annotation.Nullable String prefix) throws ApiException {
        okhttp3.Call localVarCall = deleteLabelFromSpaceValidateBeforeCall(spaceKey, name, prefix, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Remove label from a space (asynchronously)
     * 
     * @param spaceKey The key of the space to remove a labels from. (required)
     * @param name The name of the label to remove (required)
     * @param prefix The prefix of the label to remove. If not provided defaults to global. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Returned if the label was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if; - The user does not provide a label name </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteLabelFromSpaceAsync(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nonnull String name, @javax.annotation.Nullable String prefix, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteLabelFromSpaceValidateBeforeCall(spaceKey, name, prefix, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for deletePageTree
     * @param id The ID of the content which forms root of the page tree, to be deleted. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Returned if the request to trash content and all its current page descendants, is successfully accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the content id is invalid or id does not represents a &#39;CURRENT&#39; page. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect or missing from the request. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can not delete the content with specified id. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The requesting user does not have permission to trash the content or any of it&#39;s descendant pages. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePageTreeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/content/{id}/pageTree"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletePageTreeValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deletePageTree(Async)");
        }

        return deletePageTreeCall(id, _callback);

    }

    /**
     * Delete page tree
     * Moves a pagetree rooted at a page to the space&#39;s trash:  - If the content&#39;s type is &#x60;page&#x60; and its status is &#x60;current&#x60;, it will be trashed including all its descendants. - For every other combination of content type and status, this API is not supported.  This API accepts the pageTree delete request and returns a task ID. The delete process happens asynchronously.   Response example:  &lt;pre&gt;&lt;code&gt;  {       \&quot;id\&quot; : \&quot;1180606\&quot;,       \&quot;links\&quot; : {            \&quot;status\&quot; : \&quot;/rest/api/longtask/1180606\&quot;       }  }  &lt;/code&gt;&lt;/pre&gt;  Use the &#x60;/longtask/&lt;taskId&gt;&#x60; REST API to get the copy task status.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#39;Delete&#39; permission for the space that the content is in.
     * @param id The ID of the content which forms root of the page tree, to be deleted. (required)
     * @return LongTask
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Returned if the request to trash content and all its current page descendants, is successfully accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the content id is invalid or id does not represents a &#39;CURRENT&#39; page. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect or missing from the request. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can not delete the content with specified id. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The requesting user does not have permission to trash the content or any of it&#39;s descendant pages. </td><td>  -  </td></tr>
     </table>
     */
    public LongTask deletePageTree(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<LongTask> localVarResp = deletePageTreeWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Delete page tree
     * Moves a pagetree rooted at a page to the space&#39;s trash:  - If the content&#39;s type is &#x60;page&#x60; and its status is &#x60;current&#x60;, it will be trashed including all its descendants. - For every other combination of content type and status, this API is not supported.  This API accepts the pageTree delete request and returns a task ID. The delete process happens asynchronously.   Response example:  &lt;pre&gt;&lt;code&gt;  {       \&quot;id\&quot; : \&quot;1180606\&quot;,       \&quot;links\&quot; : {            \&quot;status\&quot; : \&quot;/rest/api/longtask/1180606\&quot;       }  }  &lt;/code&gt;&lt;/pre&gt;  Use the &#x60;/longtask/&lt;taskId&gt;&#x60; REST API to get the copy task status.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#39;Delete&#39; permission for the space that the content is in.
     * @param id The ID of the content which forms root of the page tree, to be deleted. (required)
     * @return ApiResponse&lt;LongTask&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Returned if the request to trash content and all its current page descendants, is successfully accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the content id is invalid or id does not represents a &#39;CURRENT&#39; page. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect or missing from the request. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can not delete the content with specified id. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The requesting user does not have permission to trash the content or any of it&#39;s descendant pages. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LongTask> deletePageTreeWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = deletePageTreeValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<LongTask>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete page tree (asynchronously)
     * Moves a pagetree rooted at a page to the space&#39;s trash:  - If the content&#39;s type is &#x60;page&#x60; and its status is &#x60;current&#x60;, it will be trashed including all its descendants. - For every other combination of content type and status, this API is not supported.  This API accepts the pageTree delete request and returns a task ID. The delete process happens asynchronously.   Response example:  &lt;pre&gt;&lt;code&gt;  {       \&quot;id\&quot; : \&quot;1180606\&quot;,       \&quot;links\&quot; : {            \&quot;status\&quot; : \&quot;/rest/api/longtask/1180606\&quot;       }  }  &lt;/code&gt;&lt;/pre&gt;  Use the &#x60;/longtask/&lt;taskId&gt;&#x60; REST API to get the copy task status.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#39;Delete&#39; permission for the space that the content is in.
     * @param id The ID of the content which forms root of the page tree, to be deleted. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Returned if the request to trash content and all its current page descendants, is successfully accepted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Returned if the content id is invalid or id does not represents a &#39;CURRENT&#39; page. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the authentication credentials are incorrect or missing from the request. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Returned if the calling user can not delete the content with specified id. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no content with the given ID. - The requesting user does not have permission to trash the content or any of it&#39;s descendant pages. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePageTreeAsync(@javax.annotation.Nonnull String id, final ApiCallback<LongTask> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletePageTreeValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<LongTask>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLabelsForSpace
     * @param spaceKey The key of the space to get labels for. (required)
     * @param prefix Filters the results to labels with the specified prefix. If this parameter is not specified, then labels with any prefix will be returned.  - &#x60;global&#x60; prefix is used by labels that are on content within the provided space. - &#x60;my&#x60; prefix can be explicitly added by a user when adding a label via the UI, e.g. &#39;my:example-label&#39;. - &#x60;team&#x60; prefix is used for labels applied to the space. (optional)
     * @param start The starting index of the returned labels. (optional, default to 0)
     * @param limit The maximum number of labels to return per page. Note, this may be restricted by fixed system limits. (optional, default to 200)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the list of labels is returned. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLabelsForSpaceCall(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/space/{spaceKey}/label"
            .replace("{" + "spaceKey" + "}", localVarApiClient.escapeString(spaceKey.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (prefix != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("prefix", prefix));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLabelsForSpaceValidateBeforeCall(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'spaceKey' is set
        if (spaceKey == null) {
            throw new ApiException("Missing the required parameter 'spaceKey' when calling getLabelsForSpace(Async)");
        }

        return getLabelsForSpaceCall(spaceKey, prefix, start, limit, _callback);

    }

    /**
     * Get Space Labels
     * Returns a list of labels associated with a space. Can provide a prefix as well as other filters to select different types of labels.
     * @param spaceKey The key of the space to get labels for. (required)
     * @param prefix Filters the results to labels with the specified prefix. If this parameter is not specified, then labels with any prefix will be returned.  - &#x60;global&#x60; prefix is used by labels that are on content within the provided space. - &#x60;my&#x60; prefix can be explicitly added by a user when adding a label via the UI, e.g. &#39;my:example-label&#39;. - &#x60;team&#x60; prefix is used for labels applied to the space. (optional)
     * @param start The starting index of the returned labels. (optional, default to 0)
     * @param limit The maximum number of labels to return per page. Note, this may be restricted by fixed system limits. (optional, default to 200)
     * @return LabelArray
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the list of labels is returned. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public LabelArray getLabelsForSpace(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<LabelArray> localVarResp = getLabelsForSpaceWithHttpInfo(spaceKey, prefix, start, limit);
        return localVarResp.getData();
    }

    /**
     * Get Space Labels
     * Returns a list of labels associated with a space. Can provide a prefix as well as other filters to select different types of labels.
     * @param spaceKey The key of the space to get labels for. (required)
     * @param prefix Filters the results to labels with the specified prefix. If this parameter is not specified, then labels with any prefix will be returned.  - &#x60;global&#x60; prefix is used by labels that are on content within the provided space. - &#x60;my&#x60; prefix can be explicitly added by a user when adding a label via the UI, e.g. &#39;my:example-label&#39;. - &#x60;team&#x60; prefix is used for labels applied to the space. (optional)
     * @param start The starting index of the returned labels. (optional, default to 0)
     * @param limit The maximum number of labels to return per page. Note, this may be restricted by fixed system limits. (optional, default to 200)
     * @return ApiResponse&lt;LabelArray&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the list of labels is returned. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LabelArray> getLabelsForSpaceWithHttpInfo(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = getLabelsForSpaceValidateBeforeCall(spaceKey, prefix, start, limit, null);
        Type localVarReturnType = new TypeToken<LabelArray>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Space Labels (asynchronously)
     * Returns a list of labels associated with a space. Can provide a prefix as well as other filters to select different types of labels.
     * @param spaceKey The key of the space to get labels for. (required)
     * @param prefix Filters the results to labels with the specified prefix. If this parameter is not specified, then labels with any prefix will be returned.  - &#x60;global&#x60; prefix is used by labels that are on content within the provided space. - &#x60;my&#x60; prefix can be explicitly added by a user when adding a label via the UI, e.g. &#39;my:example-label&#39;. - &#x60;team&#x60; prefix is used for labels applied to the space. (optional)
     * @param start The starting index of the returned labels. (optional, default to 0)
     * @param limit The maximum number of labels to return per page. Note, this may be restricted by fixed system limits. (optional, default to 200)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the list of labels is returned. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if; - There is no space with the given space key. - The calling user does not have permission to view the space. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLabelsForSpaceAsync(@javax.annotation.Nonnull String spaceKey, @javax.annotation.Nullable String prefix, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit, final ApiCallback<LabelArray> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLabelsForSpaceValidateBeforeCall(spaceKey, prefix, start, limit, _callback);
        Type localVarReturnType = new TypeToken<LabelArray>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
