/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiCallback;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiClient;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.invoker.ApiResponse;
import io.kestra.plugin.atlassian_confluence.client.invoker.Configuration;
import io.kestra.plugin.atlassian_confluence.client.invoker.Pair;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressRequestBody;
import io.kestra.plugin.atlassian_confluence.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.kestra.plugin.atlassian_confluence.client.model.LongTaskStatusArray;
import io.kestra.plugin.atlassian_confluence.client.model.LongTaskStatusWithLinks;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LongRunningTaskApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LongRunningTaskApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LongRunningTaskApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getTask
     * @param id The ID of the task. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested task is returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no task with the given ID. - The calling user does not have permission to view the task. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTaskCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/longtask/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTaskValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getTask(Async)");
        }

        return getTaskCall(id, _callback);

    }

    /**
     * Get long-running task
     * Returns information about an active long-running task (e.g. space export), such as how long it has been running and the percentage of the task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     * @param id The ID of the task. (required)
     * @return LongTaskStatusWithLinks
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested task is returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no task with the given ID. - The calling user does not have permission to view the task. </td><td>  -  </td></tr>
     </table>
     */
    public LongTaskStatusWithLinks getTask(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<LongTaskStatusWithLinks> localVarResp = getTaskWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get long-running task
     * Returns information about an active long-running task (e.g. space export), such as how long it has been running and the percentage of the task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     * @param id The ID of the task. (required)
     * @return ApiResponse&lt;LongTaskStatusWithLinks&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested task is returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no task with the given ID. - The calling user does not have permission to view the task. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LongTaskStatusWithLinks> getTaskWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getTaskValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<LongTaskStatusWithLinks>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get long-running task (asynchronously)
     * Returns information about an active long-running task (e.g. space export), such as how long it has been running and the percentage of the task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     * @param id The ID of the task. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested task is returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returned if;  - There is no task with the given ID. - The calling user does not have permission to view the task. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTaskAsync(@javax.annotation.Nonnull String id, final ApiCallback<LongTaskStatusWithLinks> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTaskValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<LongTaskStatusWithLinks>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTasks
     * @param key The key of the tasks. (optional)
     * @param start The starting index of the returned tasks. (optional, default to 0)
     * @param limit The maximum number of tasks to return per page. Note, this may be restricted by fixed system limits. (optional, default to 100)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested tasks are returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTasksCall(@javax.annotation.Nullable String key, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/wiki/rest/api/longtask";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (key != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("key", key));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "oAuthDefinitions" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTasksValidateBeforeCall(@javax.annotation.Nullable String key, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        return getTasksCall(key, start, limit, _callback);

    }

    /**
     * Get long-running tasks
     * Returns information about all active long-running tasks (e.g. space export), such as how long each task has been running and the percentage of each task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     * @param key The key of the tasks. (optional)
     * @param start The starting index of the returned tasks. (optional, default to 0)
     * @param limit The maximum number of tasks to return per page. Note, this may be restricted by fixed system limits. (optional, default to 100)
     * @return LongTaskStatusArray
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested tasks are returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
     </table>
     */
    public LongTaskStatusArray getTasks(@javax.annotation.Nullable String key, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<LongTaskStatusArray> localVarResp = getTasksWithHttpInfo(key, start, limit);
        return localVarResp.getData();
    }

    /**
     * Get long-running tasks
     * Returns information about all active long-running tasks (e.g. space export), such as how long each task has been running and the percentage of each task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     * @param key The key of the tasks. (optional)
     * @param start The starting index of the returned tasks. (optional, default to 0)
     * @param limit The maximum number of tasks to return per page. Note, this may be restricted by fixed system limits. (optional, default to 100)
     * @return ApiResponse&lt;LongTaskStatusArray&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested tasks are returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LongTaskStatusArray> getTasksWithHttpInfo(@javax.annotation.Nullable String key, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = getTasksValidateBeforeCall(key, start, limit, null);
        Type localVarReturnType = new TypeToken<LongTaskStatusArray>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get long-running tasks (asynchronously)
     * Returns information about all active long-running tasks (e.g. space export), such as how long each task has been running and the percentage of each task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     * @param key The key of the tasks. (optional)
     * @param start The starting index of the returned tasks. (optional, default to 0)
     * @param limit The maximum number of tasks to return per page. Note, this may be restricted by fixed system limits. (optional, default to 100)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returned if the requested tasks are returned. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Returned if the calling user is not logged in to Confluence. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTasksAsync(@javax.annotation.Nullable String key, @javax.annotation.Nullable Integer start, @javax.annotation.Nullable Integer limit, final ApiCallback<LongTaskStatusArray> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTasksValidateBeforeCall(key, start, limit, _callback);
        Type localVarReturnType = new TypeToken<LongTaskStatusArray>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
