/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.ContentMetadataCurrentuserExpandable;
import io.kestra.plugin.atlassian_confluence.client.model.ContentMetadataCurrentuserFavourited;
import io.kestra.plugin.atlassian_confluence.client.model.ContentMetadataCurrentuserLastcontributed;
import io.kestra.plugin.atlassian_confluence.client.model.ContentMetadataCurrentuserLastmodified;
import io.kestra.plugin.atlassian_confluence.client.model.ContentMetadataCurrentuserViewed;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContentMetadataCurrentuser
 */
public class ContentMetadataCurrentuserTest {
    private final ContentMetadataCurrentuser model = new ContentMetadataCurrentuser();

    /**
     * Model tests for ContentMetadataCurrentuser
     */
    @Test
    public void testContentMetadataCurrentuser() {
        // TODO: test ContentMetadataCurrentuser
    }

    /**
     * Test the property 'favourited'
     */
    @Test
    public void favouritedTest() {
        // TODO: test favourited
    }

    /**
     * Test the property 'lastmodified'
     */
    @Test
    public void lastmodifiedTest() {
        // TODO: test lastmodified
    }

    /**
     * Test the property 'lastcontributed'
     */
    @Test
    public void lastcontributedTest() {
        // TODO: test lastcontributed
    }

    /**
     * Test the property 'viewed'
     */
    @Test
    public void viewedTest() {
        // TODO: test viewed
    }

    /**
     * Test the property 'scheduled'
     */
    @Test
    public void scheduledTest() {
        // TODO: test scheduled
    }

    /**
     * Test the property 'expandable'
     */
    @Test
    public void expandableTest() {
        // TODO: test expandable
    }

}
