/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.ContentHistoryContributors;
import io.kestra.plugin.atlassian_confluence.client.model.ContentHistoryExpandable;
import io.kestra.plugin.atlassian_confluence.client.model.GenericLinksValue;
import io.kestra.plugin.atlassian_confluence.client.model.User;
import io.kestra.plugin.atlassian_confluence.client.model.Version;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContentHistory
 */
public class ContentHistoryTest {
    private final ContentHistory model = new ContentHistory();

    /**
     * Model tests for ContentHistory
     */
    @Test
    public void testContentHistory() {
        // TODO: test ContentHistory
    }

    /**
     * Test the property 'latest'
     */
    @Test
    public void latestTest() {
        // TODO: test latest
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'ownedBy'
     */
    @Test
    public void ownedByTest() {
        // TODO: test ownedBy
    }

    /**
     * Test the property 'lastOwnedBy'
     */
    @Test
    public void lastOwnedByTest() {
        // TODO: test lastOwnedBy
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'previousVersion'
     */
    @Test
    public void previousVersionTest() {
        // TODO: test previousVersion
    }

    /**
     * Test the property 'contributors'
     */
    @Test
    public void contributorsTest() {
        // TODO: test contributors
    }

    /**
     * Test the property 'nextVersion'
     */
    @Test
    public void nextVersionTest() {
        // TODO: test nextVersion
    }

    /**
     * Test the property 'expandable'
     */
    @Test
    public void expandableTest() {
        // TODO: test expandable
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
