/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContentChildTypeExpandable
 */
public class ContentChildTypeExpandableTest {
    private final ContentChildTypeExpandable model = new ContentChildTypeExpandable();

    /**
     * Model tests for ContentChildTypeExpandable
     */
    @Test
    public void testContentChildTypeExpandable() {
        // TODO: test ContentChildTypeExpandable
    }

    /**
     * Test the property 'all'
     */
    @Test
    public void allTest() {
        // TODO: test all
    }

    /**
     * Test the property 'attachment'
     */
    @Test
    public void attachmentTest() {
        // TODO: test attachment
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'whiteboard'
     */
    @Test
    public void whiteboardTest() {
        // TODO: test whiteboard
    }

    /**
     * Test the property 'database'
     */
    @Test
    public void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'embed'
     */
    @Test
    public void embedTest() {
        // TODO: test embed
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

}
