/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.ButtonLookAndFeel;
import io.kestra.plugin.atlassian_confluence.client.model.NavigationLookAndFeel;
import io.kestra.plugin.atlassian_confluence.client.model.SearchFieldLookAndFeel;
import io.kestra.plugin.atlassian_confluence.client.model.TopNavigationLookAndFeel;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HorizontalHeaderLookAndFeel
 */
public class HorizontalHeaderLookAndFeelTest {
    private final HorizontalHeaderLookAndFeel model = new HorizontalHeaderLookAndFeel();

    /**
     * Model tests for HorizontalHeaderLookAndFeel
     */
    @Test
    public void testHorizontalHeaderLookAndFeel() {
        // TODO: test HorizontalHeaderLookAndFeel
    }

    /**
     * Test the property 'backgroundColor'
     */
    @Test
    public void backgroundColorTest() {
        // TODO: test backgroundColor
    }

    /**
     * Test the property 'button'
     */
    @Test
    public void buttonTest() {
        // TODO: test button
    }

    /**
     * Test the property 'primaryNavigation'
     */
    @Test
    public void primaryNavigationTest() {
        // TODO: test primaryNavigation
    }

    /**
     * Test the property 'secondaryNavigation'
     */
    @Test
    public void secondaryNavigationTest() {
        // TODO: test secondaryNavigation
    }

    /**
     * Test the property 'search'
     */
    @Test
    public void searchTest() {
        // TODO: test search
    }

}
