/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.model.ArchivePagesRequest;
import io.kestra.plugin.atlassian_confluence.client.model.Content;
import io.kestra.plugin.atlassian_confluence.client.model.ContentArray;
import io.kestra.plugin.atlassian_confluence.client.model.ContentBlueprintDraft;
import io.kestra.plugin.atlassian_confluence.client.model.LongTask;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContentApi
 */
@Disabled
public class ContentApiTest {

    private final ContentApi api = new ContentApi();

    /**
     * Archive pages
     *
     * Archives a list of pages. The pages to be archived are specified as a list of content IDs. This API accepts the archival request and returns a task ID. The archival process happens asynchronously. Use the /longtask/&lt;taskId&gt; REST API to get the copy task status.  Each content ID needs to resolve to page objects that are not already in an archived state. The content IDs need not belong to the same space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#39;Archive&#39; permission for each of the pages in the corresponding space it belongs to.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void archivePagesTest() throws ApiException {
        ArchivePagesRequest archivePagesRequest = null;
        LongTask response = api.archivePages(archivePagesRequest);
        // TODO: test validations
    }

    /**
     * Publish legacy draft
     *
     * Publishes a legacy draft of a page created from a blueprint. Legacy drafts will eventually be removed in favor of shared drafts. For now, this method works the same as [Publish shared draft](#api-content-blueprint-instance-draftId-put).  By default, the following objects are expanded: &#x60;body.storage&#x60;, &#x60;history&#x60;, &#x60;space&#x60;, &#x60;version&#x60;, &#x60;ancestors&#x60;.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the draft and &#39;Add&#39; permission for the space that the content will be created in.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void publishLegacyDraftTest() throws ApiException {
        String draftId = null;
        ContentBlueprintDraft body = null;
        String status = null;
        List<String> expand = null;
        Content response = api.publishLegacyDraft(draftId, body, status, expand);
        // TODO: test validations
    }

    /**
     * Publish shared draft
     *
     * Publishes a shared draft of a page created from a blueprint.  By default, the following objects are expanded: &#x60;body.storage&#x60;, &#x60;history&#x60;, &#x60;space&#x60;, &#x60;version&#x60;, &#x60;ancestors&#x60;.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the draft and &#39;Add&#39; permission for the space that the content will be created in.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void publishSharedDraftTest() throws ApiException {
        String draftId = null;
        ContentBlueprintDraft body = null;
        String status = null;
        List<String> expand = null;
        Content response = api.publishSharedDraft(draftId, body, status, expand);
        // TODO: test validations
    }

    /**
     * Search content by CQL
     *
     * Returns the list of content that matches a Confluence Query Language (CQL) query. For information on CQL, see: [Advanced searching using CQL](https://developer.atlassian.com/cloud/confluence/advanced-searching-using-cql/).  Example initial call: &#x60;&#x60;&#x60; /wiki/rest/api/content/search?cql&#x3D;type&#x3D;page&amp;limit&#x3D;25 &#x60;&#x60;&#x60;  Example response: &#x60;&#x60;&#x60; {   \&quot;results\&quot;: [     { ... },     { ... },     ...     { ... }   ],   \&quot;limit\&quot;: 25,   \&quot;size\&quot;: 25,   ...   \&quot;_links\&quot;: {     \&quot;base\&quot;: \&quot;&lt;url&gt;\&quot;,     \&quot;context\&quot;: \&quot;&lt;url&gt;\&quot;,     \&quot;next\&quot;: \&quot;/rest/api/content/search?cql&#x3D;type&#x3D;page&amp;limit&#x3D;25&amp;cursor&#x3D;raNDoMsTRiNg\&quot;,     \&quot;self\&quot;: \&quot;&lt;url&gt;\&quot;   } } &#x60;&#x60;&#x60;  When additional results are available, returns &#x60;next&#x60; and &#x60;prev&#x60; URLs to retrieve them in subsequent calls. The URLs each contain a cursor that points to the appropriate set of results. Use &#x60;limit&#x60; to specify the number of results returned in each call. Example subsequent call (taken from example response): &#x60;&#x60;&#x60; /wiki/rest/api/content/search?cql&#x3D;type&#x3D;page&amp;limit&#x3D;25&amp;cursor&#x3D;raNDoMsTRiNg &#x60;&#x60;&#x60; The response to this will have a &#x60;prev&#x60; URL similar to the &#x60;next&#x60; in the example response.  If the expand query parameter is used with the &#x60;body.export_view&#x60; and/or &#x60;body.styled_view&#x60; properties, then the query limit parameter will be restricted to a maximum value of 25.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission). Only content that the user has permission to view will be returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchContentByCQLTest() throws ApiException {
        String cql = null;
        String cqlcontext = null;
        List<String> expand = null;
        String cursor = null;
        Integer limit = null;
        ContentArray response = api.searchContentByCQL(cql, cqlcontext, expand, cursor, limit);
        // TODO: test validations
    }

}
