/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.api;

import io.kestra.plugin.atlassian_confluence.client.invoker.ApiException;
import io.kestra.plugin.atlassian_confluence.client.model.LongTaskStatusArray;
import io.kestra.plugin.atlassian_confluence.client.model.LongTaskStatusWithLinks;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LongRunningTaskApi
 */
@Disabled
public class LongRunningTaskApiTest {

    private final LongRunningTaskApi api = new LongRunningTaskApi();

    /**
     * Get long-running task
     *
     * Returns information about an active long-running task (e.g. space export), such as how long it has been running and the percentage of the task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTaskTest() throws ApiException {
        String id = null;
        LongTaskStatusWithLinks response = api.getTask(id);
        // TODO: test validations
    }

    /**
     * Get long-running tasks
     *
     * Returns information about all active long-running tasks (e.g. space export), such as how long each task has been running and the percentage of each task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#39;Can use&#39; global permission).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTasksTest() throws ApiException {
        String key = null;
        Integer start = null;
        Integer limit = null;
        LongTaskStatusArray response = api.getTasks(key, start, limit);
        // TODO: test validations
    }

}
