/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.AffectedObject;
import io.kestra.plugin.atlassian_confluence.client.model.AuditRecordAuthor;
import io.kestra.plugin.atlassian_confluence.client.model.ChangedValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.kestra.plugin.atlassian_confluence.client.invoker.JSON;

/**
 * AuditRecord
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AuditRecord {
  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  @javax.annotation.Nonnull
  private AuditRecordAuthor author;

  public static final String SERIALIZED_NAME_REMOTE_ADDRESS = "remoteAddress";
  @SerializedName(SERIALIZED_NAME_REMOTE_ADDRESS)
  @javax.annotation.Nonnull
  private String remoteAddress;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creationDate";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  @javax.annotation.Nonnull
  private Long creationDate;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @javax.annotation.Nonnull
  private String summary;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nonnull
  private String category;

  public static final String SERIALIZED_NAME_SYS_ADMIN = "sysAdmin";
  @SerializedName(SERIALIZED_NAME_SYS_ADMIN)
  @javax.annotation.Nonnull
  private Boolean sysAdmin;

  public static final String SERIALIZED_NAME_SUPER_ADMIN = "superAdmin";
  @SerializedName(SERIALIZED_NAME_SUPER_ADMIN)
  @javax.annotation.Nullable
  private Boolean superAdmin;

  public static final String SERIALIZED_NAME_AFFECTED_OBJECT = "affectedObject";
  @SerializedName(SERIALIZED_NAME_AFFECTED_OBJECT)
  @javax.annotation.Nonnull
  private AffectedObject affectedObject;

  public static final String SERIALIZED_NAME_CHANGED_VALUES = "changedValues";
  @SerializedName(SERIALIZED_NAME_CHANGED_VALUES)
  @javax.annotation.Nonnull
  private List<ChangedValue> changedValues = new ArrayList<>();

  public static final String SERIALIZED_NAME_ASSOCIATED_OBJECTS = "associatedObjects";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_OBJECTS)
  @javax.annotation.Nonnull
  private List<AffectedObject> associatedObjects = new ArrayList<>();

  public AuditRecord() {
  }

  public AuditRecord author(@javax.annotation.Nonnull AuditRecordAuthor author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @javax.annotation.Nonnull
  public AuditRecordAuthor getAuthor() {
    return author;
  }

  public void setAuthor(@javax.annotation.Nonnull AuditRecordAuthor author) {
    this.author = author;
  }


  public AuditRecord remoteAddress(@javax.annotation.Nonnull String remoteAddress) {
    this.remoteAddress = remoteAddress;
    return this;
  }

  /**
   * Get remoteAddress
   * @return remoteAddress
   */
  @javax.annotation.Nonnull
  public String getRemoteAddress() {
    return remoteAddress;
  }

  public void setRemoteAddress(@javax.annotation.Nonnull String remoteAddress) {
    this.remoteAddress = remoteAddress;
  }


  public AuditRecord creationDate(@javax.annotation.Nonnull Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * The creation date-time of the audit record, as a timestamp.
   * @return creationDate
   */
  @javax.annotation.Nonnull
  public Long getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(@javax.annotation.Nonnull Long creationDate) {
    this.creationDate = creationDate;
  }


  public AuditRecord summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  public String getSummary() {
    return summary;
  }

  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public AuditRecord description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public AuditRecord category(@javax.annotation.Nonnull String category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nonnull
  public String getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nonnull String category) {
    this.category = category;
  }


  public AuditRecord sysAdmin(@javax.annotation.Nonnull Boolean sysAdmin) {
    this.sysAdmin = sysAdmin;
    return this;
  }

  /**
   * Get sysAdmin
   * @return sysAdmin
   */
  @javax.annotation.Nonnull
  public Boolean getSysAdmin() {
    return sysAdmin;
  }

  public void setSysAdmin(@javax.annotation.Nonnull Boolean sysAdmin) {
    this.sysAdmin = sysAdmin;
  }


  public AuditRecord superAdmin(@javax.annotation.Nullable Boolean superAdmin) {
    this.superAdmin = superAdmin;
    return this;
  }

  /**
   * Get superAdmin
   * @return superAdmin
   */
  @javax.annotation.Nullable
  public Boolean getSuperAdmin() {
    return superAdmin;
  }

  public void setSuperAdmin(@javax.annotation.Nullable Boolean superAdmin) {
    this.superAdmin = superAdmin;
  }


  public AuditRecord affectedObject(@javax.annotation.Nonnull AffectedObject affectedObject) {
    this.affectedObject = affectedObject;
    return this;
  }

  /**
   * Get affectedObject
   * @return affectedObject
   */
  @javax.annotation.Nonnull
  public AffectedObject getAffectedObject() {
    return affectedObject;
  }

  public void setAffectedObject(@javax.annotation.Nonnull AffectedObject affectedObject) {
    this.affectedObject = affectedObject;
  }


  public AuditRecord changedValues(@javax.annotation.Nonnull List<ChangedValue> changedValues) {
    this.changedValues = changedValues;
    return this;
  }

  public AuditRecord addChangedValuesItem(ChangedValue changedValuesItem) {
    if (this.changedValues == null) {
      this.changedValues = new ArrayList<>();
    }
    this.changedValues.add(changedValuesItem);
    return this;
  }

  /**
   * Get changedValues
   * @return changedValues
   */
  @javax.annotation.Nonnull
  public List<ChangedValue> getChangedValues() {
    return changedValues;
  }

  public void setChangedValues(@javax.annotation.Nonnull List<ChangedValue> changedValues) {
    this.changedValues = changedValues;
  }


  public AuditRecord associatedObjects(@javax.annotation.Nonnull List<AffectedObject> associatedObjects) {
    this.associatedObjects = associatedObjects;
    return this;
  }

  public AuditRecord addAssociatedObjectsItem(AffectedObject associatedObjectsItem) {
    if (this.associatedObjects == null) {
      this.associatedObjects = new ArrayList<>();
    }
    this.associatedObjects.add(associatedObjectsItem);
    return this;
  }

  /**
   * Get associatedObjects
   * @return associatedObjects
   */
  @javax.annotation.Nonnull
  public List<AffectedObject> getAssociatedObjects() {
    return associatedObjects;
  }

  public void setAssociatedObjects(@javax.annotation.Nonnull List<AffectedObject> associatedObjects) {
    this.associatedObjects = associatedObjects;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditRecord auditRecord = (AuditRecord) o;
    return Objects.equals(this.author, auditRecord.author) &&
        Objects.equals(this.remoteAddress, auditRecord.remoteAddress) &&
        Objects.equals(this.creationDate, auditRecord.creationDate) &&
        Objects.equals(this.summary, auditRecord.summary) &&
        Objects.equals(this.description, auditRecord.description) &&
        Objects.equals(this.category, auditRecord.category) &&
        Objects.equals(this.sysAdmin, auditRecord.sysAdmin) &&
        Objects.equals(this.superAdmin, auditRecord.superAdmin) &&
        Objects.equals(this.affectedObject, auditRecord.affectedObject) &&
        Objects.equals(this.changedValues, auditRecord.changedValues) &&
        Objects.equals(this.associatedObjects, auditRecord.associatedObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, remoteAddress, creationDate, summary, description, category, sysAdmin, superAdmin, affectedObject, changedValues, associatedObjects);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditRecord {\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    remoteAddress: ").append(toIndentedString(remoteAddress)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    sysAdmin: ").append(toIndentedString(sysAdmin)).append("\n");
    sb.append("    superAdmin: ").append(toIndentedString(superAdmin)).append("\n");
    sb.append("    affectedObject: ").append(toIndentedString(affectedObject)).append("\n");
    sb.append("    changedValues: ").append(toIndentedString(changedValues)).append("\n");
    sb.append("    associatedObjects: ").append(toIndentedString(associatedObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("author", "remoteAddress", "creationDate", "summary", "description", "category", "sysAdmin", "superAdmin", "affectedObject", "changedValues", "associatedObjects"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("author", "remoteAddress", "creationDate", "summary", "description", "category", "sysAdmin", "affectedObject", "changedValues", "associatedObjects"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuditRecord
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuditRecord.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in AuditRecord is not found in the empty JSON string", AuditRecord.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuditRecord.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuditRecord` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AuditRecord.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `author`
      AuditRecordAuthor.validateJsonElement(jsonObj.get("author"));
      if (!jsonObj.get("remoteAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `remoteAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remoteAddress").toString()));
      }
      if (!jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      // validate the required field `affectedObject`
      AffectedObject.validateJsonElement(jsonObj.get("affectedObject"));
      // ensure the json data is an array
      if (!jsonObj.get("changedValues").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `changedValues` to be an array in the JSON string but got `%s`", jsonObj.get("changedValues").toString()));
      }

      JsonArray jsonArraychangedValues = jsonObj.getAsJsonArray("changedValues");
      // validate the required field `changedValues` (array)
      for (int i = 0; i < jsonArraychangedValues.size(); i++) {
        ChangedValue.validateJsonElement(jsonArraychangedValues.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("associatedObjects").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `associatedObjects` to be an array in the JSON string but got `%s`", jsonObj.get("associatedObjects").toString()));
      }

      JsonArray jsonArrayassociatedObjects = jsonObj.getAsJsonArray("associatedObjects");
      // validate the required field `associatedObjects` (array)
      for (int i = 0; i < jsonArrayassociatedObjects.size(); i++) {
        AffectedObject.validateJsonElement(jsonArrayassociatedObjects.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditRecord.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditRecord' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditRecord> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditRecord.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditRecord>() {
           @Override
           public void write(JsonWriter out, AuditRecord value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditRecord read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuditRecord given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuditRecord
   * @throws IOException if the JSON string is invalid with respect to AuditRecord
   */
  public static AuditRecord fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditRecord.class);
  }

  /**
   * Convert an instance of AuditRecord to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

