/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.ContentBodyConversionInput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.kestra.plugin.atlassian_confluence.client.invoker.JSON;

/**
 * BulkContentBodyConversionInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BulkContentBodyConversionInput {
  public static final String SERIALIZED_NAME_CONVERSION_INPUTS = "conversionInputs";
  @SerializedName(SERIALIZED_NAME_CONVERSION_INPUTS)
  @javax.annotation.Nullable
  private List<ContentBodyConversionInput> conversionInputs = new ArrayList<>();

  public BulkContentBodyConversionInput() {
  }

  public BulkContentBodyConversionInput conversionInputs(@javax.annotation.Nullable List<ContentBodyConversionInput> conversionInputs) {
    this.conversionInputs = conversionInputs;
    return this;
  }

  public BulkContentBodyConversionInput addConversionInputsItem(ContentBodyConversionInput conversionInputsItem) {
    if (this.conversionInputs == null) {
      this.conversionInputs = new ArrayList<>();
    }
    this.conversionInputs.add(conversionInputsItem);
    return this;
  }

  /**
   * Get conversionInputs
   * @return conversionInputs
   */
  @javax.annotation.Nullable
  public List<ContentBodyConversionInput> getConversionInputs() {
    return conversionInputs;
  }

  public void setConversionInputs(@javax.annotation.Nullable List<ContentBodyConversionInput> conversionInputs) {
    this.conversionInputs = conversionInputs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkContentBodyConversionInput bulkContentBodyConversionInput = (BulkContentBodyConversionInput) o;
    return Objects.equals(this.conversionInputs, bulkContentBodyConversionInput.conversionInputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conversionInputs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkContentBodyConversionInput {\n");
    sb.append("    conversionInputs: ").append(toIndentedString(conversionInputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("conversionInputs"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BulkContentBodyConversionInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BulkContentBodyConversionInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in BulkContentBodyConversionInput is not found in the empty JSON string", BulkContentBodyConversionInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BulkContentBodyConversionInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BulkContentBodyConversionInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("conversionInputs") != null && !jsonObj.get("conversionInputs").isJsonNull()) {
        JsonArray jsonArrayconversionInputs = jsonObj.getAsJsonArray("conversionInputs");
        if (jsonArrayconversionInputs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("conversionInputs").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `conversionInputs` to be an array in the JSON string but got `%s`", jsonObj.get("conversionInputs").toString()));
          }

          // validate the optional field `conversionInputs` (array)
          for (int i = 0; i < jsonArrayconversionInputs.size(); i++) {
            ContentBodyConversionInput.validateJsonElement(jsonArrayconversionInputs.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkContentBodyConversionInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkContentBodyConversionInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkContentBodyConversionInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkContentBodyConversionInput.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkContentBodyConversionInput>() {
           @Override
           public void write(JsonWriter out, BulkContentBodyConversionInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkContentBodyConversionInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BulkContentBodyConversionInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BulkContentBodyConversionInput
   * @throws IOException if the JSON string is invalid with respect to BulkContentBodyConversionInput
   */
  public static BulkContentBodyConversionInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkContentBodyConversionInput.class);
  }

  /**
   * Convert an instance of BulkContentBodyConversionInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

