/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.ContentBody;
import io.kestra.plugin.atlassian_confluence.client.model.ContentChildType;
import io.kestra.plugin.atlassian_confluence.client.model.ContentChildren;
import io.kestra.plugin.atlassian_confluence.client.model.ContentExpandable;
import io.kestra.plugin.atlassian_confluence.client.model.ContentHistory;
import io.kestra.plugin.atlassian_confluence.client.model.ContentMetadata;
import io.kestra.plugin.atlassian_confluence.client.model.ContentRestrictions;
import io.kestra.plugin.atlassian_confluence.client.model.GenericLinksValue;
import io.kestra.plugin.atlassian_confluence.client.model.OperationCheckResult;
import io.kestra.plugin.atlassian_confluence.client.model.Space;
import io.kestra.plugin.atlassian_confluence.client.model.Version;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.kestra.plugin.atlassian_confluence.client.invoker.JSON;

/**
 * Base object for all content types.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Content {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_SPACE = "space";
  @SerializedName(SERIALIZED_NAME_SPACE)
  @javax.annotation.Nullable
  private Space space;

  public static final String SERIALIZED_NAME_HISTORY = "history";
  @SerializedName(SERIALIZED_NAME_HISTORY)
  @javax.annotation.Nullable
  private ContentHistory history;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private Version version;

  public static final String SERIALIZED_NAME_ANCESTORS = "ancestors";
  @SerializedName(SERIALIZED_NAME_ANCESTORS)
  @javax.annotation.Nullable
  private List<Content> ancestors;

  public static final String SERIALIZED_NAME_OPERATIONS = "operations";
  @SerializedName(SERIALIZED_NAME_OPERATIONS)
  @javax.annotation.Nullable
  private List<OperationCheckResult> operations = new ArrayList<>();

  public static final String SERIALIZED_NAME_CHILDREN = "children";
  @SerializedName(SERIALIZED_NAME_CHILDREN)
  @javax.annotation.Nullable
  private ContentChildren children;

  public static final String SERIALIZED_NAME_CHILD_TYPES = "childTypes";
  @SerializedName(SERIALIZED_NAME_CHILD_TYPES)
  @javax.annotation.Nullable
  private ContentChildType childTypes;

  public static final String SERIALIZED_NAME_DESCENDANTS = "descendants";
  @SerializedName(SERIALIZED_NAME_DESCENDANTS)
  @javax.annotation.Nullable
  private ContentChildren descendants;

  public static final String SERIALIZED_NAME_CONTAINER = "container";
  @SerializedName(SERIALIZED_NAME_CONTAINER)
  @javax.annotation.Nullable
  private Map<String, Object> container;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  @javax.annotation.Nullable
  private ContentBody body;

  public static final String SERIALIZED_NAME_RESTRICTIONS = "restrictions";
  @SerializedName(SERIALIZED_NAME_RESTRICTIONS)
  @javax.annotation.Nullable
  private ContentRestrictions restrictions;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private ContentMetadata metadata;

  public static final String SERIALIZED_NAME_MACRO_RENDERED_OUTPUT = "macroRenderedOutput";
  @SerializedName(SERIALIZED_NAME_MACRO_RENDERED_OUTPUT)
  @javax.annotation.Nullable
  private Map<String, Object> macroRenderedOutput = new HashMap<>();

  public static final String SERIALIZED_NAME_EXTENSIONS = "extensions";
  @SerializedName(SERIALIZED_NAME_EXTENSIONS)
  @javax.annotation.Nullable
  private Object extensions;

  public static final String SERIALIZED_NAME_EXPANDABLE = "_expandable";
  @SerializedName(SERIALIZED_NAME_EXPANDABLE)
  @javax.annotation.Nullable
  private ContentExpandable expandable;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nullable
  private Map<String, GenericLinksValue> links = new HashMap<>();

  public Content() {
  }

  public Content id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Content type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Can be \&quot;page\&quot;, \&quot;blogpost\&quot;, \&quot;attachment\&quot; or \&quot;content\&quot;
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public Content status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }


  public Content title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public Content space(@javax.annotation.Nullable Space space) {
    this.space = space;
    return this;
  }

  /**
   * Get space
   * @return space
   */
  @javax.annotation.Nullable
  public Space getSpace() {
    return space;
  }

  public void setSpace(@javax.annotation.Nullable Space space) {
    this.space = space;
  }


  public Content history(@javax.annotation.Nullable ContentHistory history) {
    this.history = history;
    return this;
  }

  /**
   * Get history
   * @return history
   */
  @javax.annotation.Nullable
  public ContentHistory getHistory() {
    return history;
  }

  public void setHistory(@javax.annotation.Nullable ContentHistory history) {
    this.history = history;
  }


  public Content version(@javax.annotation.Nullable Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Version getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable Version version) {
    this.version = version;
  }


  public Content ancestors(@javax.annotation.Nullable List<Content> ancestors) {
    this.ancestors = ancestors;
    return this;
  }

  public Content addAncestorsItem(Content ancestorsItem) {
    if (this.ancestors == null) {
      this.ancestors = new ArrayList<>();
    }
    this.ancestors.add(ancestorsItem);
    return this;
  }

  /**
   * Get ancestors
   * @return ancestors
   */
  @javax.annotation.Nullable
  public List<Content> getAncestors() {
    return ancestors;
  }

  public void setAncestors(@javax.annotation.Nullable List<Content> ancestors) {
    this.ancestors = ancestors;
  }


  public Content operations(@javax.annotation.Nullable List<OperationCheckResult> operations) {
    this.operations = operations;
    return this;
  }

  public Content addOperationsItem(OperationCheckResult operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<>();
    }
    this.operations.add(operationsItem);
    return this;
  }

  /**
   * Get operations
   * @return operations
   */
  @javax.annotation.Nullable
  public List<OperationCheckResult> getOperations() {
    return operations;
  }

  public void setOperations(@javax.annotation.Nullable List<OperationCheckResult> operations) {
    this.operations = operations;
  }


  public Content children(@javax.annotation.Nullable ContentChildren children) {
    this.children = children;
    return this;
  }

  /**
   * Get children
   * @return children
   */
  @javax.annotation.Nullable
  public ContentChildren getChildren() {
    return children;
  }

  public void setChildren(@javax.annotation.Nullable ContentChildren children) {
    this.children = children;
  }


  public Content childTypes(@javax.annotation.Nullable ContentChildType childTypes) {
    this.childTypes = childTypes;
    return this;
  }

  /**
   * Get childTypes
   * @return childTypes
   */
  @javax.annotation.Nullable
  public ContentChildType getChildTypes() {
    return childTypes;
  }

  public void setChildTypes(@javax.annotation.Nullable ContentChildType childTypes) {
    this.childTypes = childTypes;
  }


  public Content descendants(@javax.annotation.Nullable ContentChildren descendants) {
    this.descendants = descendants;
    return this;
  }

  /**
   * Get descendants
   * @return descendants
   */
  @javax.annotation.Nullable
  public ContentChildren getDescendants() {
    return descendants;
  }

  public void setDescendants(@javax.annotation.Nullable ContentChildren descendants) {
    this.descendants = descendants;
  }


  public Content container(@javax.annotation.Nullable Map<String, Object> container) {
    this.container = container;
    return this;
  }

  public Content putContainerItem(String key, Object containerItem) {
    if (this.container == null) {
      this.container = new HashMap<>();
    }
    this.container.put(key, containerItem);
    return this;
  }

  /**
   * Container for content. This can be either a space (containing a page or blogpost) or a page/blog post (containing an attachment or comment)
   * @return container
   */
  @javax.annotation.Nullable
  public Map<String, Object> getContainer() {
    return container;
  }

  public void setContainer(@javax.annotation.Nullable Map<String, Object> container) {
    this.container = container;
  }


  public Content body(@javax.annotation.Nullable ContentBody body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nullable
  public ContentBody getBody() {
    return body;
  }

  public void setBody(@javax.annotation.Nullable ContentBody body) {
    this.body = body;
  }


  public Content restrictions(@javax.annotation.Nullable ContentRestrictions restrictions) {
    this.restrictions = restrictions;
    return this;
  }

  /**
   * Get restrictions
   * @return restrictions
   */
  @javax.annotation.Nullable
  public ContentRestrictions getRestrictions() {
    return restrictions;
  }

  public void setRestrictions(@javax.annotation.Nullable ContentRestrictions restrictions) {
    this.restrictions = restrictions;
  }


  public Content metadata(@javax.annotation.Nullable ContentMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  public ContentMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable ContentMetadata metadata) {
    this.metadata = metadata;
  }


  public Content macroRenderedOutput(@javax.annotation.Nullable Map<String, Object> macroRenderedOutput) {
    this.macroRenderedOutput = macroRenderedOutput;
    return this;
  }

  public Content putMacroRenderedOutputItem(String key, Object macroRenderedOutputItem) {
    if (this.macroRenderedOutput == null) {
      this.macroRenderedOutput = new HashMap<>();
    }
    this.macroRenderedOutput.put(key, macroRenderedOutputItem);
    return this;
  }

  /**
   * Get macroRenderedOutput
   * @return macroRenderedOutput
   */
  @javax.annotation.Nullable
  public Map<String, Object> getMacroRenderedOutput() {
    return macroRenderedOutput;
  }

  public void setMacroRenderedOutput(@javax.annotation.Nullable Map<String, Object> macroRenderedOutput) {
    this.macroRenderedOutput = macroRenderedOutput;
  }


  public Content extensions(@javax.annotation.Nullable Object extensions) {
    this.extensions = extensions;
    return this;
  }

  /**
   * Get extensions
   * @return extensions
   */
  @javax.annotation.Nullable
  public Object getExtensions() {
    return extensions;
  }

  public void setExtensions(@javax.annotation.Nullable Object extensions) {
    this.extensions = extensions;
  }


  public Content expandable(@javax.annotation.Nullable ContentExpandable expandable) {
    this.expandable = expandable;
    return this;
  }

  /**
   * Get expandable
   * @return expandable
   */
  @javax.annotation.Nullable
  public ContentExpandable getExpandable() {
    return expandable;
  }

  public void setExpandable(@javax.annotation.Nullable ContentExpandable expandable) {
    this.expandable = expandable;
  }


  public Content links(@javax.annotation.Nullable Map<String, GenericLinksValue> links) {
    this.links = links;
    return this;
  }

  public Content putLinksItem(String key, GenericLinksValue linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public Map<String, GenericLinksValue> getLinks() {
    return links;
  }

  public void setLinks(@javax.annotation.Nullable Map<String, GenericLinksValue> links) {
    this.links = links;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Content instance itself
   */
  public Content putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Content content = (Content) o;
    return Objects.equals(this.id, content.id) &&
        Objects.equals(this.type, content.type) &&
        Objects.equals(this.status, content.status) &&
        Objects.equals(this.title, content.title) &&
        Objects.equals(this.space, content.space) &&
        Objects.equals(this.history, content.history) &&
        Objects.equals(this.version, content.version) &&
        Objects.equals(this.ancestors, content.ancestors) &&
        Objects.equals(this.operations, content.operations) &&
        Objects.equals(this.children, content.children) &&
        Objects.equals(this.childTypes, content.childTypes) &&
        Objects.equals(this.descendants, content.descendants) &&
        Objects.equals(this.container, content.container) &&
        Objects.equals(this.body, content.body) &&
        Objects.equals(this.restrictions, content.restrictions) &&
        Objects.equals(this.metadata, content.metadata) &&
        Objects.equals(this.macroRenderedOutput, content.macroRenderedOutput) &&
        Objects.equals(this.extensions, content.extensions) &&
        Objects.equals(this.expandable, content.expandable) &&
        Objects.equals(this.links, content.links)&&
        Objects.equals(this.additionalProperties, content.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, status, title, space, history, version, ancestors, operations, children, childTypes, descendants, container, body, restrictions, metadata, macroRenderedOutput, extensions, expandable, links, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Content {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    space: ").append(toIndentedString(space)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    ancestors: ").append(toIndentedString(ancestors)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    childTypes: ").append(toIndentedString(childTypes)).append("\n");
    sb.append("    descendants: ").append(toIndentedString(descendants)).append("\n");
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    restrictions: ").append(toIndentedString(restrictions)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    macroRenderedOutput: ").append(toIndentedString(macroRenderedOutput)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("    expandable: ").append(toIndentedString(expandable)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "type", "status", "title", "space", "history", "version", "ancestors", "operations", "children", "childTypes", "descendants", "container", "body", "restrictions", "metadata", "macroRenderedOutput", "extensions", "_expandable", "_links"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Content
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Content.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Content is not found in the empty JSON string", Content.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Content.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      // validate the optional field `space`
      if (jsonObj.get("space") != null && !jsonObj.get("space").isJsonNull()) {
        Space.validateJsonElement(jsonObj.get("space"));
      }
      // validate the optional field `history`
      if (jsonObj.get("history") != null && !jsonObj.get("history").isJsonNull()) {
        ContentHistory.validateJsonElement(jsonObj.get("history"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("ancestors") != null && !jsonObj.get("ancestors").isJsonNull() && !jsonObj.get("ancestors").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `ancestors` to be an array in the JSON string but got `%s`", jsonObj.get("ancestors").toString()));
      }
      if (jsonObj.get("operations") != null && !jsonObj.get("operations").isJsonNull()) {
        JsonArray jsonArrayoperations = jsonObj.getAsJsonArray("operations");
        if (jsonArrayoperations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("operations").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `operations` to be an array in the JSON string but got `%s`", jsonObj.get("operations").toString()));
          }

          // validate the optional field `operations` (array)
          for (int i = 0; i < jsonArrayoperations.size(); i++) {
            OperationCheckResult.validateJsonElement(jsonArrayoperations.get(i));
          };
        }
      }
      // validate the optional field `body`
      if (jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull()) {
        ContentBody.validateJsonElement(jsonObj.get("body"));
      }
      // validate the optional field `restrictions`
      if (jsonObj.get("restrictions") != null && !jsonObj.get("restrictions").isJsonNull()) {
        ContentRestrictions.validateJsonElement(jsonObj.get("restrictions"));
      }
      // validate the optional field `_expandable`
      if (jsonObj.get("_expandable") != null && !jsonObj.get("_expandable").isJsonNull()) {
        ContentExpandable.validateJsonElement(jsonObj.get("_expandable"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Content.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Content' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Content> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Content.class));

       return (TypeAdapter<T>) new TypeAdapter<Content>() {
           @Override
           public void write(JsonWriter out, Content value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Content read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             Content instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Content given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Content
   * @throws IOException if the JSON string is invalid with respect to Content
   */
  public static Content fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Content.class);
  }

  /**
   * Convert an instance of Content to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

