/*
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.plugin.atlassian_confluence.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kestra.plugin.atlassian_confluence.client.model.OperationCheckResult;
import io.kestra.plugin.atlassian_confluence.client.model.SpacePermissionCreateSubjects;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import io.kestra.plugin.atlassian_confluence.client.invoker.JSON;

/**
 * This object represents a permission for given space. Permissions consist of at least one operation object with an accompanying subjects object.  The following combinations of &#x60;operation&#x60; and &#x60;targetType&#x60; values are valid for the &#x60;operation&#x60; object:    - &#39;create&#39;: &#39;page&#39;, &#39;blogpost&#39;, &#39;comment&#39;, &#39;attachment&#39;   - &#39;read&#39;: &#39;space&#39;   - &#39;delete&#39;: &#39;page&#39;, &#39;blogpost&#39;, &#39;comment&#39;, &#39;attachment&#39;   - &#39;export&#39;: &#39;space&#39;   - &#39;administer&#39;: &#39;space&#39;
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SpacePermissionCreate {
  public static final String SERIALIZED_NAME_SUBJECTS = "subjects";
  @SerializedName(SERIALIZED_NAME_SUBJECTS)
  @javax.annotation.Nullable
  private SpacePermissionCreateSubjects subjects;

  public static final String SERIALIZED_NAME_OPERATION = "operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  @javax.annotation.Nonnull
  private OperationCheckResult operation;

  public static final String SERIALIZED_NAME_ANONYMOUS_ACCESS = "anonymousAccess";
  @SerializedName(SERIALIZED_NAME_ANONYMOUS_ACCESS)
  @javax.annotation.Nonnull
  private Boolean anonymousAccess = false;

  public static final String SERIALIZED_NAME_UNLICENSED_ACCESS = "unlicensedAccess";
  @SerializedName(SERIALIZED_NAME_UNLICENSED_ACCESS)
  @javax.annotation.Nonnull
  private Boolean unlicensedAccess = false;

  public SpacePermissionCreate() {
  }

  public SpacePermissionCreate subjects(@javax.annotation.Nullable SpacePermissionCreateSubjects subjects) {
    this.subjects = subjects;
    return this;
  }

  /**
   * Get subjects
   * @return subjects
   */
  @javax.annotation.Nullable
  public SpacePermissionCreateSubjects getSubjects() {
    return subjects;
  }

  public void setSubjects(@javax.annotation.Nullable SpacePermissionCreateSubjects subjects) {
    this.subjects = subjects;
  }


  public SpacePermissionCreate operation(@javax.annotation.Nonnull OperationCheckResult operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Get operation
   * @return operation
   */
  @javax.annotation.Nonnull
  public OperationCheckResult getOperation() {
    return operation;
  }

  public void setOperation(@javax.annotation.Nonnull OperationCheckResult operation) {
    this.operation = operation;
  }


  public SpacePermissionCreate anonymousAccess(@javax.annotation.Nonnull Boolean anonymousAccess) {
    this.anonymousAccess = anonymousAccess;
    return this;
  }

  /**
   * Grant anonymous users permission to use the operation.
   * @return anonymousAccess
   */
  @javax.annotation.Nonnull
  public Boolean getAnonymousAccess() {
    return anonymousAccess;
  }

  public void setAnonymousAccess(@javax.annotation.Nonnull Boolean anonymousAccess) {
    this.anonymousAccess = anonymousAccess;
  }


  public SpacePermissionCreate unlicensedAccess(@javax.annotation.Nonnull Boolean unlicensedAccess) {
    this.unlicensedAccess = unlicensedAccess;
    return this;
  }

  /**
   * Grants access to unlicensed users from JIRA Service Desk when used with the &#39;read space&#39; operation.
   * @return unlicensedAccess
   */
  @javax.annotation.Nonnull
  public Boolean getUnlicensedAccess() {
    return unlicensedAccess;
  }

  public void setUnlicensedAccess(@javax.annotation.Nonnull Boolean unlicensedAccess) {
    this.unlicensedAccess = unlicensedAccess;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SpacePermissionCreate instance itself
   */
  public SpacePermissionCreate putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpacePermissionCreate spacePermissionCreate = (SpacePermissionCreate) o;
    return Objects.equals(this.subjects, spacePermissionCreate.subjects) &&
        Objects.equals(this.operation, spacePermissionCreate.operation) &&
        Objects.equals(this.anonymousAccess, spacePermissionCreate.anonymousAccess) &&
        Objects.equals(this.unlicensedAccess, spacePermissionCreate.unlicensedAccess)&&
        Objects.equals(this.additionalProperties, spacePermissionCreate.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subjects, operation, anonymousAccess, unlicensedAccess, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpacePermissionCreate {\n");
    sb.append("    subjects: ").append(toIndentedString(subjects)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    anonymousAccess: ").append(toIndentedString(anonymousAccess)).append("\n");
    sb.append("    unlicensedAccess: ").append(toIndentedString(unlicensedAccess)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("subjects", "operation", "anonymousAccess", "unlicensedAccess"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("operation", "anonymousAccess", "unlicensedAccess"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SpacePermissionCreate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SpacePermissionCreate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in SpacePermissionCreate is not found in the empty JSON string", SpacePermissionCreate.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SpacePermissionCreate.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `subjects`
      if (jsonObj.get("subjects") != null && !jsonObj.get("subjects").isJsonNull()) {
        SpacePermissionCreateSubjects.validateJsonElement(jsonObj.get("subjects"));
      }
      // validate the required field `operation`
      OperationCheckResult.validateJsonElement(jsonObj.get("operation"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SpacePermissionCreate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SpacePermissionCreate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SpacePermissionCreate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SpacePermissionCreate.class));

       return (TypeAdapter<T>) new TypeAdapter<SpacePermissionCreate>() {
           @Override
           public void write(JsonWriter out, SpacePermissionCreate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SpacePermissionCreate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SpacePermissionCreate instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SpacePermissionCreate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SpacePermissionCreate
   * @throws IOException if the JSON string is invalid with respect to SpacePermissionCreate
   */
  public static SpacePermissionCreate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SpacePermissionCreate.class);
  }

  /**
   * Convert an instance of SpacePermissionCreate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

